CREATE TABLE Serverlist
(
IPid INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
IP VARCHAR(200),
OS VARCHAR(200),
CPUamount INT,
Name VARCHAR(200),
OriginalName VARCHAR(200),
ChildrenCount VARCHAR(200),
HostType VARCHAR(200),
ParentID VARCHAR(200)
) ENGINE=InnoDB;

